train:
  epochs: 10
  batch_size: 8
  lr: 0.001
  num_workers: 0  # Windows系统建议设为0，避免多进程报错
  device: "cuda"
  lr_step_size: 3  # 每3个epoch调整一次学习率
  lr_gamma: 0.5    # 学习率乘以0.5

data:
  root: "./data"
  num_classes: 2
  img_size: 224

save:
  log_dir: "./work_dirs/logs"
  ckpt_dir: "./work_dirs/ckpt"